# Generated by Django 4.1.7 on 2023-03-31 01:42

from django.db import migrations

def populate_status(apps, schemaeditor):
    defaults = {
        "To Do": "Issue is yet to be addressed.",
        "In Progress": "Issue is being dealt with.",
        "Done": "Issue has been resolved."
    }
    Status = apps.get_model("issues", "Status")
    for key, desc in defaults.items():
        status_obj = Status(name=key, description=desc)
        status_obj.save()


def populate_priority(apps, schemaeditor):
    defaults = {
        "Low": "Issue is not critical.",
        "Medium": "Issue is important, but not critical",
        "High": "Issue is critical."
    }
    Priority = apps.get_model("issues", "Priority")
    for key, desc in defaults.items():
        priority_obj = Priority(name=key, description=desc)
        priority_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status),
        migrations.RunPython(populate_priority)
    ]
